USE FINANCE
GO

--1. Tính doanh thu, net profit, profit margin chung cho từng tháng
CREATE VIEW VW_OVERVIEW AS (
	SELECT 
		MONTH(F.DATE) AS MONTH, SUM(AMOUNT) AS NET_PROFIT,
		SUM(CASE WHEN F.Revenue_or_expense = 'REVENUE' THEN F.AMOUNT ELSE 0 END) AS TOTAL_REVENUE,
		ABS(SUM(CASE WHEN F.Revenue_or_expense = 'EXPENSE' AND F.Group_ID = 3 THEN F.AMOUNT ELSE 0 END)) AS TOTAL_COGS,
		ABS(SUM(CASE WHEN F.Revenue_or_expense = 'EXPENSE' AND F.Group_ID = 2 THEN F.AMOUNT ELSE 0 END)) AS TOTAL_OPEX,
        SUM(CASE WHEN F.Revenue_or_expense = 'EXPENSE' THEN F.AMOUNT ELSE 0 END) AS TOTAL_EXPENSE,
		LAG(SUM(AMOUNT)) OVER(ORDER BY MONTH(F.DATE)) AS PRE_PROFIT
	FROM FACT F
	GROUP BY MONTH(F.DATE)
)

SELECT 
	MONTH, TOTAL_REVENUE, TOTAL_EXPENSE, NET_PROFIT, 
	(NET_PROFIT - PRE_PROFIT)*100/PRE_PROFIT AS GROWTH,
	CASE 
		WHEN TOTAL_REVENUE = 0 THEN 0
		ELSE NET_PROFIT*100/TOTAL_REVENUE
	END AS NET_PROFIT_MARGIN
FROM VW_OVERVIEW
ORDER BY MONTH


--2. Tính doanh thu cho cả năm, group by theo business line, tháng năm 
CREATE VIEW VW_LINE AS (
	SELECT 
		BL.Business_Line AS LINE, SUM(AMOUNT) AS NET_PROFIT,
		SUM(CASE WHEN F.Revenue_or_expense = 'REVENUE' THEN F.AMOUNT ELSE 0 END) AS TOTAL_REVENUE,
        ABS(SUM(CASE WHEN F.Revenue_or_expense = 'EXPENSE' AND F.Group_ID = 3 THEN F.AMOUNT ELSE 0 END)) AS TOTAL_COGS,
		ABS(SUM(CASE WHEN F.Revenue_or_expense = 'EXPENSE' AND F.Group_ID = 2 THEN F.AMOUNT ELSE 0 END)) AS TOTAL_OPEX,
		ABS(SUM(CASE WHEN F.Revenue_or_expense = 'EXPENSE' THEN F.AMOUNT ELSE 0 END)) AS TOTAL_EXPENSE
	FROM FACT F
	JOIN [Business Line] BL
	ON BL.Business_Line_ID = F.Business_Line_ID
	GROUP BY BL.Business_Line
)

SELECT 
	LINE, TOTAL_REVENUE, TOTAL_COGS, TOTAL_OPEX, TOTAL_EXPENSE, NET_PROFIT, 
	CASE 
		WHEN TOTAL_REVENUE = 0 THEN 0
		ELSE NET_PROFIT*100/TOTAL_REVENUE
	END AS NET_PROFIT_MARGIN
FROM VW_LINE
ORDER BY LINE


--3. Tính doanh thu cho cả năm, group by theo nguồn doanh thu, tháng năm 
CREATE VIEW VW_REVENUE_SOURCE AS (
	SELECT 
		F.SUBGROUP_ID, SG.Subgroup AS REVENUE_SOURCE, MONTH(F.DATE) AS MONTH,
		SUM(F.AMOUNT) AS TOTAL_REVENUE
	FROM FACT F
	JOIN SUBGROUP SG
	ON SG.Subgroup_ID = F.SUBGROUP_ID
	WHERE F.Revenue_or_expense = 'REVENUE'
	GROUP BY F.SUBGROUP_ID, SG.Subgroup, MONTH(F.DATE)
)

SELECT REVENUE_SOURCE, MONTH, TOTAL_REVENUE 
FROM VW_REVENUE_SOURCE
ORDER BY REVENUE_SOURCE, MONTH


--4. ROI
CREATE VIEW VW_ROI_ANALYSIS AS
WITH TOTAL_REV AS (
    -- Tính tổng Revenue riêng ra một hằng số
    SELECT SUM(AMOUNT) AS TOTAL_VAL 
    FROM FACT 
    WHERE Revenue_or_expense = 'REVENUE'
)
SELECT 
    SG.Subgroup_ID AS ID, SG.Subgroup AS EXPENSE_TYPE,
    MAX(TR.TOTAL_VAL) AS TOTAL_REVENUE, -- Dùng MAX hoặc MIN vì TOTAL_VAL là hằng số từ CROSS JOIN
	ABS(SUM(F.AMOUNT)) AS TOTAL_EXPENSE,
    -- Tính tỷ lệ phần trăm
    ABS((SUM(F.AMOUNT)) * 100.0) / NULLIF(MAX(TR.TOTAL_VAL), 0) AS ROI
FROM FACT F
JOIN SUBGROUP SG ON SG.Subgroup_ID = F.SUBGROUP_ID
CROSS JOIN TOTAL_REV TR 
WHERE F.Revenue_or_expense = 'EXPENSE'
GROUP BY SG.Subgroup_ID, SG.Subgroup
ORDER BY SG.Subgroup_ID


--5. Scenario
CREATE VIEW PL AS 
SELECT 
		SUM(AMOUNT) AS NET_PROFIT,
		SUM(CASE WHEN F.Revenue_or_expense = 'REVENUE' THEN F.AMOUNT ELSE 0 END) AS TOTAL_REVENUE,
		ABS(SUM(CASE WHEN F.Revenue_or_expense = 'EXPENSE' AND F.Group_ID = 3 THEN F.AMOUNT ELSE 0 END)) AS TOTAL_COGS,
		ABS(SUM(CASE WHEN F.Revenue_or_expense = 'EXPENSE' AND F.Group_ID = 2 THEN F.AMOUNT ELSE 0 END)) AS TOTAL_OPEX,
        SUM(CASE WHEN F.Revenue_or_expense = 'EXPENSE' THEN F.AMOUNT ELSE 0 END) AS TOTAL_EXPENSE
	FROM FACT F


CREATE PROC PROFIT_SIMULATION
    @rev_growth FLOAT,
    @cogs_growth FLOAT,
    @opex_growth FLOAT
AS
BEGIN
    SELECT 
        NET_PROFIT AS CURRENT_PROFIT,
		TOTAL_REVENUE * (1 + @rev_growth) 
        - TOTAL_COGS * (1 + @cogs_growth)
        - TOTAL_OPEX * (1 + @opex_growth)
        AS NEW_PROFIT,
		CAST(((
			TOTAL_REVENUE * (1 + @rev_growth)
            - TOTAL_COGS * (1 + @cogs_growth)
            - TOTAL_OPEX * (1 + @opex_growth)
		) 
		- NET_PROFIT) * 100.0 / NULLIF(NET_PROFIT, 0)
        AS DECIMAL(10,2)) AS PERCENT_CHANGE
    FROM PL
END

EXEC PROFIT_SIMULATION 0.05, 0.05, 0.10;
EXEC PROFIT_SIMULATION 0.10, 0.03, 0.05